Parameters: 
  InstanceType:
    Default: t2.micro
    Type: String
    Description: Sizing for EC2 Instances
  KeyName:
    Default: vockey
    Type: String
    Description: Key to access EC2 Instances via SSH
  Stage:
    Default: dev
    Type: String
    Description: Default Environment to Create
  BlueWeight:
    Default: 1
    Type: String
    Description: LB Weight for Blue Instance(s)
  GreenWeight:
    Default: 1
    Type: String
    Description: LB Weight for Green Instance(s)

Resources:
  
# Target Group, Listener and Application  Load Balancer
  BlueTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 15
      HealthyThresholdCount: 5
      Matcher:
        HttpCode: '200,302'
      Name: BlueTargetGroup
      HealthCheckPath: '/BookManagement'
      Port: 8080
      Protocol: HTTP
      TargetGroupAttributes:
      - Key: deregistration_delay.timeout_seconds
        Value: '20'
      TargetType: ip
      UnhealthyThresholdCount: 3
      VpcId: !ImportValue book-management-vpc
  
  BlueTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      ExecutionRoleArn: LabRole
      ContainerDefinitions:
        - Name: BookManagement
          Image: '872884872117.dkr.ecr.us-east-1.amazonaws.com/bookmanagement:latest'
          Essential: true
          PortMappings:
            - HostPort: 8080
              Protocol: tcp
              ContainerPort: 8080
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Cpu: '256'
      Memory: '512'
      Family: ecs-demo
  ECSDemoCluster:
    Type: 'AWS::ECS::Cluster'
    Properties: 
      ClusterName: BookManagementCluster
  ECSDemoService:
    Type: 'AWS::ECS::Service'
    DependsOn: ALBListener
    Properties:
      ServiceName: BookManagementService
      Cluster: !Ref ECSDemoCluster
      DesiredCount: 1
      TaskDefinition: !Ref BlueTaskDefinition
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: BookManagement
          ContainerPort: 8080
          TargetGroupArn: !Ref BlueTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - !ImportValue book-management-security-WebServerSecurityGroupId
          Subnets:
            - !ImportValue book-management-vpc-PublicSubnet1
            - !ImportValue book-management-vpc-PublicSubnet2

# Target Group, Listener and Application  Load Balancer

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref BlueTargetGroup
                Weight: !Ref BlueWeight
              
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
      - !ImportValue book-management-vpc-PublicSubnet1
      - !ImportValue book-management-vpc-PublicSubnet2
      SecurityGroups:
        - !ImportValue book-management-security-WebServerSecurityGroupId

Outputs:
  LoadBalancerURL:
    Description: "URL to access our Tomcat Server"
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - ApplicationLoadBalancer
          - DNSName
        - '/BookManagement'
    Export:
      Name: !Sub "${AWS::StackName}-TomcatURL"