Resources:
  BookWebEIPDev:
    Type: AWS::EC2::EIP
    Properties:
      Tags: 
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-dev"
  BookWebEIPStaging:
    Type: AWS::EC2::EIP
    Properties:
      Tags: 
        - Key: "Name"
          Value: !Sub "${AWS::StackName}-staging"
Outputs: 
  WebEIPDev:
    Description: Elastic IP for our Web Server
    Value: !Ref BookWebEIPDev
    Export:
      Name: !Sub "BookWebEIP-${AWS::StackName}-dev"
  WebEIPStaging:
    Description: Elastic IP for our Web Server
    Value: !Ref BookWebEIPStaging 
    Export:
      Name: !Sub "BookWebEIP-${AWS::StackName}-staging"