virtualmachines:
  hosts:
    book_management_web:
      ansible_host: 54.163.128.202
      ansible_user: ec2-user

    web-blue:
      ansible_host: 54.163.128.202 
      ansible_user: ec2-user
      sudo: yes
    web-green:
      ansible_host: 54.162.187.214
      ansible_user: ec2-user
      sudo: yes

    jenkins:
      ansible_host: 44.214.23.187
      ansible_user: ubuntu