- name: Test user management
  hosts: web
  tasks:
   - name: Check that you can connect (GET) to a page and it returns a status 200
     ansible.builtin.uri:
        url: http://44.214.23.117:8080/BookManagement
